version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: postgres_database

    env_file:
      - ./src/.env

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
